### ISSUE TITLE
Reading inputs from file

### ISSUE THREAD

**Issue by TudorLesanHP** [openscore/score-language#105]
I suggest having for example the key --fi (file inputs) or --if (inputs file)

Having both options specified this scenario will happen:
 - the inputs specified in the CLI will overwrite the ones read from the file.

ScoreServicesImpl class will handle reading the inputs from the file.

WDYT @meirwah , @orius123 @avimora

**Comment by meirwah** [comment]
does this relate to the SystemProperties feature? @avimora ?

**Comment by avimora** [comment]
In case of similar file formats loading the file(s) should be the same

**Comment by orius123** [comment]
Right. Except we shouldn't pass it to the run method as sys props, but as inputs.

**Comment by TudorLesanHP** [comment]
what file formats should be supported?

**Comment by orius123** [comment]
I would go with .yaml and .yml

**Comment by TudorLesanHP** [comment]
do you think there should be an implicit lookup for input files, similar to system properties implementation?

**Comment by avimora** [comment]
Fixed by PR #113
