### ISSUE TITLE
change CLI to support specific extenasions as does the Slang verifier

### ISSUE THREAD

**Issue by oritstone** [openscore/score-language#111]
Support only:
- sl
- sl.yaml
- sl.yml

Do not support other extensions

**Comment by TudorLesanHP** [comment]
At what point to we want the error to occur? I can check right in the run method of SlangCLI before anything compiles and just show a message, or maybe throw an error in CompilerHelperImpl. ATM I implemented the first approach.

**Comment by TudorLesanHP** [comment]
Also as FilenameUtils.getExtension does return just extensions from files like "file.extension" (not "file.extension.extension") I had to implement a custom method. If anyone knows a better suited library for this action I would appreciate it :).

**Comment by oritstone** [comment]
Look at *SlangContentVerifier*. 
You can still use *FileUtils.listFiles()*, and pass as the file extensions: *{"sl", "sl.yaml", "sl.yml"}*

**Comment by tudorlesan** [comment]
FileUtils.listFiles() gets all the files with that specific extension from a directory(parent directory of the file given in the CLI). Afterwards I have to iterate them and check that my file is among them. If the file is in a directory that contains a lot more files then it might not be very efficient.

Wouldn't it be easier just to substring the given filename from the first "." to get the extension and just check it corresponds to the ones we are looking for?

**Comment by meshipeer** [comment]
@oritstone please review
