### ISSUE TITLE
SlangCLI editing not working properly

### ISSUE THREAD

**Issue by tudorlesan** [openscore/score-language#114]
We have a flow that executes with the following command:

run  --f flow.sl --i input=value     - which just prints input to the screen.

Let's say we want to reexecute this flow by pressing the up arrow key so the last executed command gets on the CLI screen.
Now if for example we press backspace, it doesn't delete a character, only if we press it twice, but it actually deleted it the first time only the CLI didn't show that. 

Example: Run our flow to print "value1" then reexecute it to print "value2"

- execute - run  --f flow.sl --i input=value1 = prints "value1"
- press up arrow key - command is  - run  --f flow.sl --i input=value1
- press backspace - command is still - run  --f flow.sl --i input=value1
- press backspace - command is - run  --f flow.sl --i input=value
- press 2 - command is - run --f flow.sl --i input=value2
- execute - run --f flow.sl --i input=value2 = prints "valu2" - not that we wanted

I'm guessing this is actually a problem from Spring Shell. Maybe we should take a better approach
Also Spring Shell doesn't allow us to use space for input values. For example there is no way for executing the SSH command ls -l from the CLI.

@meirwah @orius123 thoughts?

**Comment by avimora** [comment]
is it on windows?

**Comment by orius123** [comment]
can you estimate how much effort is it to stop using `Spring Shell`, and implement it ourselves?

**Comment by TudorLesanHP** [comment]
@avimora yes it's on windows. @orius123 I think you were right.. about two weeks.

**Comment by avimora** [comment]
If you have horizontal scroll bar in your windows cmd terminal you might experience strange behavior of the cursor & lines going over each other
To work around disable horizontal scroll by setting screen buffer size width same as windows size width:
(click on the cmd icon -> properties)

**Comment by oritstone** [comment]
pending #120 -replacing CLI FW
