### ISSUE TITLE
Expression doesn't throw exceptions

### ISSUE THREAD

**Issue by orius123** [openscore/score-language#119]
Evaluating expression in slang catching exceptions and printing to log instead of throwing.
it might be right in case of non-required input but not for other cases.
@openscore/developers WDYT?

**Comment by avimora** [comment]
It's better to delegate the exception to a higher level

**Comment by oritstone** [comment]
We shouldn't catch exceptions to script evaluation. It hides possible errors in the script itself.
If the problem is missing non required input, we need to think about the best solution for this use-case

**Comment by meirwah** [comment]
what about this logic:
if it is required throw exception (but the eval exception  , not missing input)
if not : ignore exception, because, do we want to fail flow on an not required input?

**Comment by orius123** [comment]
If we can distinguish between empty/null response to an exception I believe it is best

**Comment by oritstone** [comment]
:+1:
