### ISSUE TITLE
Convention in namespaces

### ISSUE THREAD

**Issue by varelasavela** [openscore/score-language#122]
For now namespace can contain spaces, "-" , "_" and capital letters.
Should be any convention in namespace like in "java" for example ?

Also may be the namespace  should be  written  all inl lower case (The validator which checks that the path ends with namespace should be insensitive)

**Comment by meshipeer** [comment]
@oritstone WDYT?

**Comment by oritstone** [comment]
- I think that the best practice should be that the namespace is with lower case letters and no special chars, but I'm not sure we should enforce it (@orius123, so you think o/w). We should add it to our content best practices
- Regarding the content verifier, I think that when validation that the namespace matches the directory structure, it should be case insensitive

**Comment by orius123** [comment]
I would go with lower case letters + dash and underscore.

**Comment by oritstone** [comment]
But do you think we should enforce it, or only document it as best practice?

**Comment by orius123** [comment]
I take it back no dash. Meaning no special chars only lower case and underscore. I don't see a reason to fail compilation let me know if you do. Verifier should notify with a warning or anything like it.
