### ISSUE TITLE
Inputs containing spaces can not be passed in the CLI

### ISSUE THREAD

**Issue by SSgtMendel** [openscore/score-language#129]
Values containing space(s) can not be passed into an input when triggering a flow in the CLI.

Multiple combinations using both " and ' have been tried without success.

CLI version: 0.1.11-SNAPSHOT

Please see attached screenshot:
![inputs_with_spaces_issue](https://cloud.githubusercontent.com/assets/11193662/6371893/c5d29170-bd08-11e4-9bdf-5fbabecffc02.JPG)

**Comment by oritstone** [comment]
pending #120 -replacing CLI FW
