### ISSUE TITLE
Linux executable is missing permissions... can not use slang on Linux

### ISSUE THREAD

**Issue by meirwah** [openscore/score-language#14]
Chmod issue?

**Comment by orius123** [comment]
I think it's completely normal.
unless we distribute/install it somehow.
suggest to close

**Comment by meirwah** [comment]
i solved it in the end with zipping in on a linux machine...
on future release we might be better by releasing 2 artifacts , 1 zip for win and 1 tar for linux

**Comment by yogabitze** [comment]
@meirwah 
Be aware that when you creating jar file that you should enable the compress option. By default jar file is only wrapping a multiple files without compression.
