### ISSUE TITLE
For loops over maps from a file seem to not work

### ISSUE THREAD

**Issue by oritstone** [openscore/score-language#143]
When trying to do a for loop on values from a system property file, or from an input file to the CLI, I couldn't make it work.
When parsing the resource file, we get a *LinkedHashMap* object. 
We can use in the slang files some iterable over it like: entrySet(), keys() or values(), but all are non Serilaizable.
So I couldn't find a way to make it work...

**Comment by oritstone** [comment]
@orius123

**Comment by meirwah** [comment]
Do we want to handle now? @oritstone @orius123 ?

**Comment by orius123** [comment]
I think it is a pretty big issue.
I say we should handle it now

**Comment by meirwah** [comment]
ok, so @Bonczidai  handle this after the MI tech design  (or if you are blocked on something..)
