### ISSUE TITLE
app_test_operations.yaml breaks too early

### ISSUE THREAD

**Issue by avigail-oron** [openscore/score-language#15]
score-language/score-language-tests/src/test/resources/yaml/docker-demo/app_test_operations.yaml
in line #31  - in case the call to the application URL did not fail, the count is set to max_count even though  this is not the case.
in addition, 'returnResult' is misleading since the code actually means 'returnResultOK'

**Comment by meirwah** [comment]
Please review @avigail-oron ...

**Comment by avigail-oron** [comment]
reviewed. now it is much more clear.
note that you populate the error msg anyway, is that the intention? why not leave it empty in case of success?
