### ISSUE TITLE
score version is hard coded in the CLI

### ISSUE THREAD

**Issue by meirwah** [openscore/score-language#16]
look at class SlangCLI param SCORE_VERSION...

**Comment by meirwah** [comment]
need to take last slang version here.. either take it from the "pom.xml" version... or somewhere else...

**Comment by meirwah** [comment]
@avimora can you review this?

**Comment by meirwah** [comment]
maybe the version should be taken from the the slang main pom.xml ?

**Comment by Bonczidai** [comment]
In this solution the version is assigned in the application.properties file from the project main pom.xml, this way it accessible before and after packaging.
There are other possible solutions:
-   after packaging the pom.xml is saved in META-INF\maven\io.openscore.lang\score-lang-cli\ - does not contain the slang version properties, probably we could define here - this solution does not work before packaging
- maybe from the Manifast file - complicate parsing
 .. after lot of research I think this is the safest way to do this, but I am open for suggestions
