### ISSUE TITLE
Outputs fix

### ISSUE THREAD

**Issue by tudorlesan** [openscore/score-language#165]
Path logic was changed. The flow outputs were printed based on what the PATH key was. It was expecting "0/0" but now the actual value is 0. EXEC_START_PATH constant inside SyncTriggerEventListener class has to be changed.

**Comment by oritstone** [comment]
@tudorlesan is the issue already fixed? Can we close it?

**Comment by tudorlesan** [comment]
@oritstone yes it can be closed.
