### ISSUE TITLE
Need to update group.id to "io.openscore"

### ISSUE THREAD

**Issue by meirwah** [openscore/score-language#22]
After the change,
we need to upload the artifact to maven central @hararzafrir  , and then update the website @orius123

**Comment by meirwah** [comment]
@hararzafrir can you upload the last artifact(of score-language) to maven central?

**Comment by meirwah** [comment]
So i understand from @hararzafrir  it is now in Mvaen Central, we just need to verify iy works, and update the website, so i'm moving this to @orius123 ...

**Comment by orius123** [comment]
you changed only group id, not packages, right?

**Comment by meirwah** [comment]
right
