### ISSUE TITLE
same task name in flow - legit?

### ISSUE THREAD

**Issue by meirwah** [openscore/score-language#3]
i created a flow like this with these tasks  :
    get_used_images:
      do:
        ops.get_used_images:
          - all_containers_ids
    get_used_images2:
      do:
        ops.get_used_images2:
          - all_containers_ids
      publish:
        - usedImages: imageList
    get_used_images:
      do:
        ops.get_used_images:
          - all_containers_ids: usedImages

meanning same task name twice, result is that last task is not executed at all..
should this fail in compile time? or be supported and is a bug??

**Comment by orius123** [comment]
I think we should fail compilation when @avimora  will handle compiler errors

**Comment by orius123** [comment]
+1 for this issue. really annoying!!

**Comment by meshipeer** [comment]
+2 for that - assigning to Avi

**Comment by orius123** [comment]
related to #28

**Comment by oritstone** [comment]
Since tasks are currently written as map properties inside the workflow, we loose the information of the duplicate tasks already at the YAML parsing level. We don't get it in the compiler.
```
workflow:
  task1:
   ...
   task1:
    ...
```
We can either change the tasks to a list:
```
workflow:
  - task1:
    ...
  - task2:
    ...
```
Or write our own parser.
@orius123  and everyone else, WDYT?

**Comment by orius123** [comment]
I think it should be a list anyways since order is meaningful

**Comment by meirwah** [comment]
list
