### ISSUE TITLE
Compiler Error Handling

### ISSUE THREAD

**Issue by oritstone** [openscore/score-language#34]
@meshipeer @meirwah @orius123 @avimora @avigail-oron - please review and comment

I'm working now on improving the compiler error handling.
Our error handling is based on Runtime Exceptions thrown from the relevant places in the code, containing the relevant error message.

I basically do the following:
- Simulate corrupted slang files, problematic executables, and see if we receive the error message.
- Make the error messages more comprehensive
- Add missing error messages
- Add missing more advanced validations, such as checking that all results of an executables have matching navigation in the embedding task.
- Consider improving the YAML parser error messages

1. Do you think anything is missing?
2. Currently we throw runtime exception for each compilation error. Do you think we should throw dedicated Compilation exceptions instead, so that the CLI for example show them in a different manner than the runtime exceptions, or is the message enough?

**Comment by meirwah** [comment]
:+1:  , no need for our own runtime exception IMO...

**Comment by avimora** [comment]
The message is enough IMO. Note that some are `IllegalArgumentException`s thrown by validate.

**Comment by orius123** [comment]
process seems fine to me.
I think we should try to improve parser exception, for CLI anyways.
don't like checked exceptions, prefer a result object.

**Comment by meirwah** [comment]
result object? please elborate on this....

**Comment by oritstone** [comment]
@orius123 don't you think the error message is enough?

**Comment by oritstone** [comment]
Another question - do you think we should add to the documentation examples of possible errors + error messages?

**Comment by meirwah** [comment]
NO, overkill in my opinion...

**Comment by orius123** [comment]
agree with @meirwah  if the error will be good we will not need to document them..
an object that contains the artifacts and/or the status. 
but as I said, RTE seems gr8 for me!

**Comment by meshipeer** [comment]
looks like we have a decision :)
Orit - please close it if you agree

**Comment by oritstone** [comment]
Agree :)
I think will leave the issue open until I merge the branch of the compiler error handling

**Comment by oritstone** [comment]
BTW, do you think we want to keep the 2 types of exceptions:
RuntimeException & IllegalArgumentException?
Or do we want to align all to RuntimeException?

**Comment by orius123** [comment]
Since illegal... extends RTE, I think we don't need to remove it. on the other hand, validate also throws nullPointerException when validating nulls as far as I remember, and that doesn't look good..

**Comment by avimora** [comment]
Or may be have dedicated unchecked exception (which extends RTE), this way additional info can be added to it easily.
