### ISSUE TITLE
What to do with slang content from score-language repo?

### ISSUE THREAD

**Issue by TudorLesanHP** [openscore/score-language#37]
I recently moved most of the Openstack/Docker slang content from score-language to slang-content and aligned it to the guidelines. Should I delete the files from score-language WDYT?

**Comment by meirwah** [comment]
Please comment @orius123 @meshipeer @oritstone , 
i think we should remove them..

**Comment by oritstone** [comment]
Agree

**Comment by orius123** [comment]
me 2

**Comment by meirwah** [comment]
@TudorLesanHP you will need also to delete all ignored test that rely on this flows...

**Comment by meirwah** [comment]
@TudorLesanHP  is this done?

**Comment by TudorLesanHP** [comment]
@meirwah yes it is. I notice the branch is deleted already

**Comment by meirwah** [comment]
please reference the fix to the issue next time...
