### ISSUE TITLE
Rename the `override` attribute on inputs

### ISSUE THREAD

**Issue by avimora** [openscore/score-language#41]
May be `force`? or invert it's meaning?

**Comment by orius123** [comment]
What is the problem with the current name

**Comment by avimora** [comment]
Confusing as raised in demo. Put your votes here :)

**Comment by avimora** [comment]
Please vote for inverting the meaning: It will be `true` by default and setting it to `false` means "Don't override this input by context".
Or if you have other suggestions...

**Comment by avimora** [comment]
Last call - please respond :8ball:

**Comment by avimora** [comment]
More alternatives: `immutable`, `lock`/`locked`

**Comment by orius123** [comment]
I fell good with override.
maybe `const` ?

**Comment by oritstone** [comment]
I don't like the override - very confusing
Regarding const - if we put an expression, I think that the word constant is also confusing.

:+1: for immutable

**Comment by avimora** [comment]
It will be renamed to `immutable` with default `false`. Setting `true` means the input won't be overridden by context.

**Comment by oritstone** [comment]
Don't forget to align all our *.sl* *.yaml* *.yml* files after the change.
You should also change all the files under the *slang-content* repository: https://github.com/openscore/slang-content

**Comment by orius123** [comment]
how is it immutable if a task `publish` ca change its value?
```yaml
flow:
  inputs: 
    - input1:
        value: "aaa"
        immutable: true
 ....

  task1:
  ....
    publish:
      - input1: "bbb"
```
**input1 = "bbb"**

**Comment by meirwah** [comment]
that is a good point.. it might be even more confusing to name it "immutable"

**Comment by avimora** [comment]
So we go with `overridable` with inversed meaning: It will be `true` by default and setting it to `false` means "Don't override this input by context".

**Comment by orius123** [comment]
@openscore/score-committers I was suuposed to review it, but I am swamped with the site stuff, can someone else review it? please?
