### ISSUE TITLE
nextPosition key of EVENT_OUTPUT_END event - map to more useful value

### ISSUE THREAD

**Issue by SamMarkowitz** [openscore/score-language#45]
When looking in the execution.log file, the nextPosition key of the EVENT_OUTPUT_END event maps to a number which is meaningless to the user. It should map to something more useful like the name of the next task to be run.

Example: `2015-01-22 09:50:55:344 53572 [WorkerExecutionThread-0_101600001] INFO  org.openscore.lang.cli.SlangCLI  - Event received: EVENT_OUTPUT_END Data is: {PATH=0/1, DESCRIPTION=Output binding finished, EXECUTIONID=101600001, TASK_NAME=division1, TIMESTAMP=Thu Jan 22 09:50:55 IST 2015, nextPosition=6, TYPE=EVENT_OUTPUT_END, RESULT=SUCCESS, OUTPUTS={ans=1.5}}`

**Comment by meirwah** [comment]
@avimora is this related to how you print the events?

**Comment by avimora** [comment]
It's actually next step id, the only navigation data available at runtime...

**Comment by meirwah** [comment]
true.. but as Sam said.. no user has what to do with it...

**Comment by avimora** [comment]
It might be useful to have it for debug/analysis purposes, so it's just a matter of display (it's only in the log anyway...)

**Comment by oritstone** [comment]
I think we need to have both

**Comment by meshipeer** [comment]
lower priority - closing this
