### ISSUE TITLE
enhancement - allow passing system props file when launching the CLI

### ISSUE THREAD

**Issue by avigail-oron** [openscore/score-language#49]
This will allow users to have a customeized script that launches the CLI with the system props built in.
Having that will make the system properties really global and reusable in the CLI, as they are potentially in the embedded lib mode.

**Comment by meirwah** [comment]
why not just add a CLI cmd to add global SP?

**Comment by avigail-oron** [comment]
I have a feeling we’re saying the same thing.

**Comment by meirwah** [comment]
@avimora this is covered by your US of SystemProp?
