### ISSUE TITLE
Support for package roots when using --cp

### ISSUE THREAD

**Issue by zsolt-donca-hp** [openscore/score-language#56]
When using flows and operations outside the current package, I need to use the --cp argument to let slang know where my .sl files are located at. 

For example, I wanted to use the operation 'base_mail' from 'org.openscore.slang.base.mail', so I needed to use the following:

--cp c:/Work/hackaton/slang-content/org/openscore/slang/base/mail

Since it's a best practice to orginaize the .sl files into folders corresponding to their namespaces, I would like to be able to point to the root of these packages, like this:

--cp c:/Work/hackaton/slang-content

**Comment by meirwah** [comment]
that should work... did you try it? and it did not work?

**Comment by zsolt-donca-hp** [comment]
We tried it yesterday during the hackaton and it didn't seem to work, but now I tried it again and it seems to work. Maybe we were still using the released version of Slang, downloaded from the official site (openscore.io), which seems to be a less developed version.

You may close this issue now.
