### ISSUE TITLE
Error messages are difficult to read because of weak of contrast in Slang console

### ISSUE THREAD

**Issue by zsolt-donca-hp** [openscore/score-language#57]
Error messages in the Slang console are difficult to read because they are colored dark red on a black background, having a weak contrast. We have found this during the Hackaton pretty annoying when doing pair programming, sitting in the front of laptop screens.

![image](https://cloud.githubusercontent.com/assets/6470373/5934845/2b078d44-a6dd-11e4-81a7-24769ac260f1.png)

I would suggest using a brighter color for error messages.

**Comment by meirwah** [comment]
like which color?
usually red is the context of error...

**Comment by zsolt-donca-hp** [comment]
A brighter red. I have checked with a color picker, and you are using the RGB color (128, 0, 0). I would suggest using (192, 0, 0) or (224, 0, 0).

**Comment by okitac** [comment]
The contrast is quite nice here, although it looks more like purple than red.
![error](https://cloud.githubusercontent.com/assets/10746606/5948894/cacb361c-a716-11e4-93f3-80d16c16e8f4.png)

**Comment by zsolt-donca-hp** [comment]
The contrast seems to be much better on this screenshot.

**Comment by oritstone** [comment]
It's a different color in the screenshot.
You can see here the 2 colors 
- red for the slang errors
- purple for spring shell errors

![image](https://cloud.githubusercontent.com/assets/7547370/5957149/1e8925e6-a7be-11e4-81da-99dce78e5530.png)

**Comment by meirwah** [comment]
seems like Ansi.Color does not support light/bright RED...
only : BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE

Either we use another library for colors, or change to a diff color from the list...

**Comment by okitac** [comment]
Or just have all errors be the same colour, and use the content to distinguish between the types of error ...

**Comment by oritstone** [comment]
pending #120 -replacing CLI FW
