### ISSUE TITLE
Prevent fqn collisions?

### ISSUE THREAD

**Issue by avimora** [openscore/score-language#60]
For example, if you have 2 operations within the dependencies with same fully qualified name, currently they will overwrite each other silently. Should the compiler prevent that?

**Comment by okitac** [comment]
Do they overwrite, or just get picked at apparent random?

**Comment by avimora** [comment]
Last one wins, but note that although snakeyaml maintain the order, according to yaml spec the order in maps is not guaranteed...

**Comment by meshipeer** [comment]
if you using our best practices you wont have this situation - closing this

**Comment by okitac** [comment]
Unless the enforcement of file name == operation name is in place, claiming that best practices keep this from being an issue is, at best, dubious.

Either way, there should be some way to find the issue other than cursing, swearing, and hoping somebody else knows what's going on :(
