### ISSUE TITLE
Quiet mode for slang-cli 'run' command

### ISSUE THREAD

**Issue by okitac** [openscore/score-language#64]
'run' currently prints out volumes of extra information that would be very awkward to use as part of a script, or anything else that parses results, eg:

```text
$ ../score-lang-cli/slang/bin/slang run division.sl --i input1=10,input2=-1
Database name is: H2 databaseMajorVersion is: 1
- divider
- printer
10/-1 = -10.0
Flow : division finished with result : SUCCESS
Jan 28, 2015 6:00:22 PM org.springframework.shell.core.AbstractShell handleExecutionResult
INFO: Flow execution time took  0:00:03.158 , with execution id : 101600001
```
A quiet mode, that only returns what is specified as output by the flow would be very useful.  In this case, that would be:
```
10/-1 = -10.0
```
Additionally (and I'll file a separate issue on this), it would be a major plus if the exit code reflected the success or failure of the flow.

**Comment by orius123** [comment]
I suggest to extended it to being able to define logging level with property.
`../slang run division.sl --log=INFO/DEBUG...`

**Comment by okitac** [comment]
Off the top of my head, putting slashes into command line options inevitably means having to escape them when scripting, and that's a `<descriptive>` pain in the `<descriptive>`.

I agree that it'd be nice to specify log levels that way, but I'd expect that to change what ends up in the slang-cli.history and execution.log files, not what shows up as a response on the command line -- so something closer to:

```
./slang run division.sl --loglevel=DEBUG --logfile=someotherlogfile.log
```
while running in quiet mode would be more along the lines of:

```
./slang run division.sl -q
```
or, for that matter, I suppose you could invert the default behaviour (which I'd actually think would be a good thing), and have the default be to only print what the flow says to print, and use something like one of the following to get more output:

```
./slang run division.sl -v
./slang run division.sl -vvv
```

Looking at that, I suppose you could also use the log levels as keywords for the amount of output information shown, eg:

```
./slang run division.sl --info
./slang run division.sl --debug
```

**Comment by meirwah** [comment]
I agree with @okitac on ***'-q'*** , but i think default behaviour should stay outputs of the flow steps
since when you work on a flow , this is (currently) our best way to debug a flow, and gives a new user the feel of whats happening (please remamber that you are already familiar with OO,, so flows are not new to you...)

**Comment by okitac** [comment]
@meirwah This gets back to one of my questions around "What are we supposed to use this for"?

If the expectation is that slang-cli is primarily an authoring tool, that makes sense -- but if we're expecting that slang-cli is a runtime scripting tool, which can also be used for authoring, that changes things.

My suggestion would be that the default in the slang-cli shell would be verbose, but the default when invoking a flow at the command line would be silent (inside slang-cli, I'd presume active authoring -- outside I'd presume being run as a utility, so to speak).

**Comment by meirwah** [comment]
i agree , it makes sense

**Comment by orius123** [comment]
I like the distinction between an interactive shell and running as script from outside.
adding the log flags `-q` or `-debug` or any other, still seems very useful for me in both cases.

**Comment by meirwah** [comment]
Please note that we also have a CLI cmd of "env --setAsync true" , whice makes the CLI to run flows in async way (so no prints of steps happen). only the print of flow end..

**Comment by okitac** [comment]
My read of the documentation below is that 'env --setAsync true' [note that it doesn't specify the 'true' in the description, only in the example, and that should probably be changed] allows me to run multiple flows at the same time, not that it in any way changes the outputs of the flow.

'''
env --setAsync - Sets the execution mode to be synchronous or asynchronous. By default the execution mode is synchronous, meaning only one flow can run at a time.
'''
I'd suggest that it's better to keep the question of whether you can run flows concurrently separate from the question of what the flow actually outputs, since it's entirely possible that you might want to run flows concurrently and verbosely (typically while testing), or concurrently and silently.

**Comment by meirwah** [comment]
ok.. that makes sense...

**Comment by TudorLesanHP** [comment]
Let's say we have a flow  and we're trying to execute it in normal then quiet mode.

![normal mode](https://cloud.githubusercontent.com/assets/8058958/6168352/50b771ca-b2cd-11e4-9a28-05f52f777d8b.png)
This would be the normal mode (everything is printed to the console)

![quiet mode](https://cloud.githubusercontent.com/assets/8058958/6168371/7b26a142-b2cd-11e4-8302-b5a006e431bf.png)
And this would be the quiet mode(notice tasks are not printed anymore, as well as execution id and duration.

Outputs are printed in both cases and I left the result of the flow to have an idea if everything went alright or not. @okitac does this suit your needs? Should I also remove the flow result/outputs?

**Comment by meirwah** [comment]
@TudorLesanHP  did you check what happens in subflow scenario? 
will it print only the parent flow outputs?

**Comment by TudorLesanHP** [comment]
@meirwah yes, it prints just parent flow outputs
