### ISSUE TITLE
slang-cli exit code is success when flow fails

### ISSUE THREAD

**Issue by okitac** [openscore/score-language#65]
slang-cli returns an exit code of 0, independent of the success or failure of the flow that has been invoked.  This makes it very annoying to try and include calls to run a flow inside of other scripting, since custom logic is then needed to determine if the flow succeeded or failed.

The flow runs successfully:
```
$ ../score-lang-cli/slang/bin/slang run division.sl --i input1=10,input2=-1
Database name is: H2 databaseMajorVersion is: 1
- divider
- printer
10/-1 = -10.0
Flow : division finished with result : SUCCESS
Jan 28, 2015 6:00:22 PM org.springframework.shell.core.AbstractShell handleExecutionResult
INFO: Flow execution time took  0:00:03.158 , with execution id : 101600001
$ echo $?
0
```

The flow fails:

```
$ ../score-lang-cli/slang/bin/slang run division.sl --i input1=10,input2=a 
Database name is: H2 databaseMajorVersion is: 1
- divider
Slang Error : Error executing python script: Traceback (most recent call last):
  File "<string>", line 4, in <module>
ValueError: invalid literal for __float__: a

Jan 28, 2015 6:10:00 PM org.springframework.shell.core.AbstractShell handleExecutionResult
INFO: Flow execution time took  0:00:02.913 , with execution id : 101600001
$ echo $?
0
```

**Comment by Bonczidai** [comment]
spring-shell does not currently support custom exit codes (http://stackoverflow.com/questions/28429223/return-custom-exit-code-in-spring-shell).

However there are two workarounds:
    - throwing an exception causes spring-shell to terminate with exit code 1
    - System.exit(code) - don't like that, killing with brute force: context may not be cleaned properly, slang prompt shuts down in interactive mode if you call this method (which is not acceptable)
    
So, currently I can't see an option to return custom exit codes according to flow results (anyway we may have any flow result not only FAILURE).

What we can (and I think should) do is throwing an exception in case of events like *Slang Error* (detected exceptions) - spring shell will catch these exceptions and modify the return code to 1

Opinions? Should I proceed with this approach?

**Comment by meirwah** [comment]
:+1: on that Levi

**Comment by orius123** [comment]
after throwing the exception will it exit, and I will have to open the shell all over again?

**Comment by Bonczidai** [comment]
no.. that's the best part about it, shell remains open (prints the exception).. but if you trigger it from cmd line like `slang run params` it will have a return code of 1

**Comment by okitac** [comment]
Sweet!  That sounds excellent!

Could you also add a note about System.exit() not cleaning up the environment, and generally being a bad idea?  [I'm presuming that applies in operations, as well -- and that the odds of somebody going off and doing it are, as often, far too good]

**Comment by orius123** [comment]
System.exit is a bad practice in java in general. But since we don't hold any open streams I don't see any particular problem except what I said about being a bad practice in general..

**Comment by Bonczidai** [comment]
After all we would need System.exit only in case of flow responses.. for errors the exception approach is good enough..

The problem however with System.exit would be that the shell would close immediately without any prompt..
