### ISSUE TITLE
Compiling a system_properties slang file throws an exception

### ISSUE THREAD

**Issue by oritstone** [openscore/score-language#66]
When sending a system_properties slang file to the compiler for compilation or pre-compilation, the compiler throws an exception, since it only knows how to compile operations & flows

**Comment by orius123** [comment]
what do you expect it to do?
there is no execution plan for system property file, and no dependencies.
I thing that returning null is not better.

**Comment by oritstone** [comment]
We need to decide what is the correct solution regarding the system properties.

If we decide that it is not compiled at all, and not validated, only run-time, we can make these files for example *.properties* files and not *.sl* files.

If we do decide that we want to compile it, and treat the properties as mandatory dependencies of the flow or operation, we need to supply some result from compiling it. For example have a parent class to Executable that includes only name, namespace and maybe something more, and return it from the *precompile()* method, and find also some construct to return from the *compile()* method.

**Comment by avimora** [comment]
Fixed by PR #94
