### ISSUE TITLE
Unclear message

### ISSUE THREAD

**Issue by Asisayag** [openscore/score-language#70]
Opening the CLI, writing only 'run' gives a not-very-clear message.
![image](https://cloud.githubusercontent.com/assets/7038610/5987305/a7f089a0-a92b-11e4-9c77-e83c9b943c85.png)

Why not showing the help menu?

**Comment by TudorLesanHP** [comment]
@Asisayag, I'm not sure how I can execute the help run command from code or even the help menu.
ATM I made the CLI to print a message for when --f is not specified or it it specified but the filepath is not given.
This is how it looks:
![run](https://cloud.githubusercontent.com/assets/8058958/6412211/97b8c598-be89-11e4-856b-dff15838a374.png)

If you think this is feasible approach I can do the same for getFlowInputs command. Also, as we are going to change from Spring Shell CLI this option will more than likely have to be reimplemented either way.

**Comment by oritstone** [comment]
pending #120 -replacing CLI FW
