### ISSUE TITLE
Space between the pararms fails the execution and gives an unclear message

### ISSUE THREAD

**Issue by Asisayag** [openscore/score-language#73]
In the following screenshot you can see two executions which the only difference between them is the space before the second parameter.  
![image](https://cloud.githubusercontent.com/assets/7038610/5987362/f2798c72-a92d-11e4-8611-d9a617752487.png)

No problem with requiring to not put a space, but the message is super-unclear.

**Comment by tudorlesan** [comment]
as far as I know this is Spring Shell's implementation so I don't know how we can change that message

**Comment by oritstone** [comment]
Duplicate #129
