### ISSUE TITLE
slang-cli error messages are unclear/unhelpful

### ISSUE THREAD

**Issue by okitac** [openscore/score-language#80]
Some of the error messages produced by slang-cli are unclear or unhelpful in resolving issues.  For example, the following actually means "your indentation is wrong"
![screen shot 2015-02-02 at 8 05 21 am](https://cloud.githubusercontent.com/assets/10746606/6003686/600a6452-aab2-11e4-9828-af963c0d8f9f.png)
In this case, "File not found" would be more helpful than "filePath must lead to a file" -- the first tells me exactly what's wrong;  the current message had me checking import statements first.
![screen shot 2015-02-02 at 8 07 44 am](https://cloud.githubusercontent.com/assets/10746606/6003740/c1fdb02e-aab2-11e4-9ac7-d854a655a6e4.png)
Here, everything is in the same directory that slang was started from, so I'm not quite sure what part it can't find (probably an include, but in theory, it should 'just work', if it's all in the same directory?)
![screen shot 2015-02-02 at 8 09 22 am](https://cloud.githubusercontent.com/assets/10746606/6003747/d5eb2936-aab2-11e4-90e3-9845b78e92d4.png)

**Comment by oritstone** [comment]
- Regarding the first issue, we are using Snake Yaml as our Yaml parser, and these are the type of errors it throws for parsing issues. We have an issue on that #43
- Fixed second issue
- Third issue means that the resource you referenced user.examples...print-sleep wasn't found in path, which is probably the case. @okitac  Maybe your operation name is wrong. Maybe you used the file name. 
We now have a new tool that will be available soon in score-language releases, that verifies that Slang files are valid, including checking:
  - files can be compiled
  - namespace = dir structure 
  - operation/flow name = file name (without extension)
