### ISSUE TITLE
RFE: add execution id to slang-cli async mode console output

### ISSUE THREAD

**Issue by okitac** [openscore/score-language#84]
When running via the slang CLI in async mode, can the execution id be included with the output?  As you can see below, it's impossible to tell which output belongs to which run at the present time.

```
slang>env --setAsync true
flow execution ASYNC execution was changed to : true
slang>run hello_world_sleep.sl
Triggered flow : hello_world_sleep , with execution id : 101600057
slang>Hello, World
slang>run hello_world_sleep.sl
Triggered flow : hello_world_sleep , with execution id : 101600062
slang>run hello_world_sleep.sl
Triggered flow : hello_world_sleep , with execution id : 101600067
slang>run hello_world_sleep.sl
Triggered flow : hello_world_sleep , with execution id : 101600072
slang>Hello, World
Hello, World
Hello, World
```

**Comment by meirwah** [comment]
Thing is thatthis flow does a print of to the stdout ,so unlike events, we can tell from which flow it arrives, BUT if you look at the events feed (in the log, execution.log) you can correlate events to execution id...

**Comment by okitac** [comment]
Could you clarify that?  I think it's clear from my example above that you can't really tell which output belongs to which flow ...

**Comment by meirwah** [comment]
sure..
So the "Hello, World" output is done using a print cmd from a python script right?
If so, this goes directlly to the stdout, so i have no way (that i can think of right now)
to correlate this to a specific flow execution id.

Usually your flows will not print to STDOUT, but send events, or have outputs specfic.
So whatever is sent as event, we can say which execution id it belongs to,

Did i make sense?

**Comment by meirwah** [comment]
@okitac  any objections for that?
i'm closing this issue otherwise...

**Comment by okitac** [comment]
I'm still not sure how I could sanely debug -- when I looked in the log, it showed me what was run, and if it succeeded or failed, but no further information.  Am I missing something obvious?

**Comment by meirwah** [comment]
if you look at a specific line:
2015-02-17 11:27:40:804 6101298 [WorkerExecutionThread-4_101600029] INFO  org.openscore.lang.cli.SlangCLI  - Event received: EVENT_OUTPUT_END Data is: {PATH=0/2, DESCRIPTION=Output binding finished, ***EXECUTIONID=101600029***, TASK_NAME=evaluate_resource_usage, TIMESTAMP=Tue Feb 17 11:27:40 IST 2015, nextPosition=0, TYPE=EVENT_OUTPUT_END, ***RESULT=SUCCESS***, ***OUTPUTS={}***}

**Comment by meirwah** [comment]
Let's close this bug.. we will add to the backlog Enhance Debugger capabilities (already have it i think)...
