### ISSUE TITLE
Variables get automatically converted to string when using them in response expressions..

### ISSUE THREAD

**Issue by TudorLesanHP** [openscore/score-language#86]
Let's say we have an operation which has as action a python_script. Inside we have variables a = 100, b = 2
If I use 
result = a < b it gets correctly evaluated to false.

But if I use 
results:
    - SUCCESS: a < b 
Then the operation succeeds since it's doing a string comparison.

**Comment by orius123** [comment]
@oritstone do you remember why we made it that way in the first place?
it seems odd to me now..

**Comment by orius123** [comment]
so do we all agree that except to the case of `@Action` that for some reason returns only strings, we should use Serializable for outputs like we do for inputs.
@meirwah @oritstone @meshipeer @avimora @TudorLesanHP @Bonczidai

**Comment by oritstone** [comment]
Agree

**Comment by avimora** [comment]
+1 assuming there is no technical issue with that
