### ISSUE TITLE
Expressions in outputs/results/publish which are not String are discarded

### ISSUE THREAD

**Issue by oritstone** [openscore/score-language#9]
@orius123 

In the outputs/publish values/ results of a flow or operation, expressions which are not String (Integer values, Boolean...) are discarded.
For example, if we have output such as:
- output1: 30
It is discarded without any error, so we will have a successful compilation, but the output will be missing from the compiled object.

Do we want to support other types?
If not, we should at least throw an exception from the compiler.

**Comment by orius123** [comment]
@oritstone Y from the compiler? it can happen also in runtime.

**Comment by oritstone** [comment]
@orius123 The problem is in the compiler - after the Outputs Transformer transform the data, outputs which are constant values which are no of String type disappear without an error.
I think it is logical to support only expressions in the outputs, so only String type.
