### ISSUE TITLE
Slang compiler does not populate ExecutionPlan subflowUUID Set

### ISSUE THREAD

**Issue by shajyhia** [openscore/score-language#92]
Slang compiler should populate ExecutionPlan subflowUUID Set for dependencies resolving later.
I think the the member subflowUUID should be renamed to dependenciesUUIDs

**Comment by meirwah** [comment]
why do you need this?

**Comment by shajyhia** [comment]
For resolving dependency later.

I think you are familiar with how triggering works and what score engine need.

[cid:image001.jpg@01D04469.06C6C890]


Resolving dependencies should be part of language compiler and today slang have the dependencies but does not populate the ExecutionPaln.subFlowUUID Set .
