### ISSUE TITLE
CLI input value cannot contain comma(,)

### ISSUE THREAD

**Issue by TudorLesanHP** [openscore/score-language#97]
I wanted to run the http_client_action operation in the CLI. The body input was JSON and should have contained commas, but that is the delimiter for the inputs.

**Comment by TudorLesanHP** [comment]
I propose using "\," for the input value. The MapConverter can firstly replace "\," with a different char/sequence of chars (like "&|" or whatever characters have less chance of appearing in the CLI) 

Then as usual the string value gets split into the different inputs with delimiter "," and afterwards that char/seq.char from each input value can be replaced back with ",". 

WDYT @meirwah @orius123

**Comment by Bonczidai** [comment]
Another suggestion:

- use syntax: --i `"normal_input=value,json_input='{\"id\": 1,\"name\": \"Foo\",\"price\": [1,2,3]}'"` 
- the MapConverter gets a string like this: `normal_input=value,json_input='{"id": 1,"name": "Foo","price": [1,2,3]}'`
- two cases in the converter:
    - normal: value
    - special: 'between marks' - take the value between marks unmodified
- note: special charachters like `"` need to be escaped, others like `,` are ok

**Comment by orius123** [comment]
Can we separate inputs with space instead of a comma?

**Comment by Bonczidai** [comment]
I think it is possible to separate inputs with space if we put the inputs between `"..."` and change of course the converter ... but that does not solve the json issue (since it contains not only commas but spaces and other characters as well)

**Comment by meirwah** [comment]
maybe give in the CLI ability to load inputs from file? like System Prop ? will solve this?

**Comment by Bonczidai** [comment]
:+1:

**Comment by orius123** [comment]
I think that passing json as string is escaping hell anyway, can we parse the inputs ourselves without wrapping with "" ?

**Comment by TudorLesanHP** [comment]
@Bonczidai you don't need to escape quotes(") in the json_input if you put it in the CLI. Also , with your solution, what if we really want the input value to contain single quotes (')

**Comment by TudorLesanHP** [comment]
@meirwah loading inputs from file will definitely solve this but I was thinking that it may be a good enhancement since we may need inputs that contain commas in the CLI.

**Comment by TudorLesanHP** [comment]
@orius123 the MapConverter just gets a string(all the inputs) and from then on we can delimit/parse it however we want.

**Comment by orius123** [comment]
if comma is a special character in out app we need to provide a way to escape it. File is another thing.

**Comment by avimora** [comment]
Fixed by PR #99
